### ISSUE TITLE
unable to install snaps on fedora 24

### ISSUE THREAD

**Issue by manik-taneja** [zyga/snapcore-fedora#4] opened 2016-06-30 16:54 UTC
the pastebin below explains the issues that i experienced on my aws fedora 24 image-

AMI ID: Fedora-Cloud-Base-24_Alpha-7.x86_64-us-west-1-HVM-standard-0 (ami-78e59718)

https://pastebin.canonical.com/159848/

in addition, i tried explicit modprobe and saw this-

Manik Taneja, [Jun 30, 2016, 9:43 AM]: 
[fedora@ip-172-31-4-4 ~]$ sudo dnf install kernel-modules
Last metadata expiration check: 1:51:55 ago on Thu Jun 30 14:51:24 2016.
Package kernel-modules-4.5.7-300.fc24.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

[fedora@ip-172-31-4-4 ~]$ sudo modprobe squashfs
modprobe: FATAL: Module squashfs not found in directory /lib/modules/4.5.0-0.rc7.git0.2.fc24.x86_64

i also tried to find a squashfs kernel module on my cloud instance but didn't find any-
find / -name "squashfs*ko" 

please review and advice..

**Comment by manik-taneja** [comment] 2016-07-08 02:03
i tried the same thing with a PV image on aws-

Fedora-Cloud-Base-24_Alpha-7.x86_64-us-west-1-PV-standard-0 (ami-70e59710)

and see the same issue as well as unable to install and snapd itself-

`[fedora@ip-172-31-7-198 ~]$ sudo dnf install snapd
Copr repo for snapcore owned by zyga                                                        116 kB/s |  21 kB     00:00    
Dependencies resolved.
============================================================================================================================
 Package                       Arch                    Version                         Repository                      Size
============================================================================================================================
Installing:
 snap-confine                  x86_64                  1.0.35-1.fc24                   zyga-snapcore                   27 k
 snapd                         x86_64                  2.0.10-2.fc24                   zyga-snapcore                  4.8 M

Transaction Summary
============================================================================================================================
Install  2 Packages

Total download size: 4.8 M
Installed size: 19 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): snap-confine-1.0.35-1.fc24.x86_64.rpm                                                121 kB/s |  27 kB     00:00    
(2/2): snapd-2.0.10-2.fc24.x86_64.rpm                                                       7.1 MB/s | 4.8 MB     00:00    
----------------------------------------------------------------------------------------------------------------------------
Total                                                                                       7.1 MB/s | 4.8 MB     00:00     
warning: /var/cache/dnf/zyga-snapcore-c14146bf6584be66/packages/snapd-2.0.10-2.fc24.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID f090a93c: NOKEY
Importing GPG key 0xF090A93C:
 Userid     : "zyga_snapcore (None) <zyga#snapcore@copr.fedorahosted.org>"
 Fingerprint: 2B0F 5C58 E963 BEAF 5ABC C2A2 AB95 BE78 F090 A93C
 From       : https://copr-be.cloud.fedoraproject.org/results/zyga/snapcore/pubkey.gpg
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : snap-confine-1.0.35-1.fc24.x86_64                                                                       1/2 
  Installing  : snapd-2.0.10-2.fc24.x86_64                                                                              2/2 
modprobe: FATAL: Module squashfs not found in directory /lib/modules/4.5.0-0.rc7.git0.2.fc24.x86_64
warning: %post(snapd-2.0.10-2.fc24.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package snapd
Non-fatal POSTIN scriptlet failure in rpm package snapd
  Verifying   : snapd-2.0.10-2.fc24.x86_64                                                                              1/2 
  Verifying   : snap-confine-1.0.35-1.fc24.x86_64                                                                       2/2 

Installed:
  snap-confine.x86_64 1.0.35-1.fc24                                snapd.x86_64 2.0.10-2.fc24                               

Complete!
`

**Comment by Conan-Kudo** [comment] 2016-08-08 19:13
@manik-taneja Does the system you're running it on indicate that something provides "squashfs.ko"?

You can check by running the following:
```bash
[~]$ rpm -q --whatprovides "kmod(squashfs.ko)"
```

**Comment by manik-taneja** [comment] 2016-08-23 00:28
@Conan-Kudo here you go-

```
[fedora@ip-172-31-5-18 ~]$ cat /proc/filesystems 
nodev	sysfs
nodev	rootfs
nodev	ramfs
nodev	bdev
nodev	proc
nodev	cpuset
nodev	cgroup
nodev	cgroup2
nodev	tmpfs
nodev	devtmpfs
nodev	configfs
nodev	debugfs
nodev	tracefs
nodev	securityfs
nodev	sockfs
nodev	bpf
nodev	pipefs
nodev	hugetlbfs
nodev	devpts
	ext3
	ext2
	ext4
nodev	autofs
nodev	pstore
nodev	mqueue
nodev	selinuxfs
	iso9660
[fedora@ip-172-31-5-18 ~]$ rpm -q --whatprovides "kmod(squashfs.ko)"
kernel-modules-4.6.6-300.fc24.x86_64
```

**Comment by zyga** [comment] 2016-08-23 18:57
I think this is fixed with the current  version of snapd in the COPR repository.

Please reopen if it happens again.

**Comment by manik-taneja** [comment] 2016-08-24 15:36
@zyga what version did you think that happened with? i tried this yesterday and failed again.

**Comment by zyga** [comment] 2016-08-24 20:17
Can you report details of what happened when you installed snapd yesterday?

**Comment by manik-taneja** [comment] 2016-08-24 22:26
`
[fedora@ip-172-31-5-18 ~]$ dnf info snapd
Last metadata expiration check: 0:03:38 ago on Wed Aug 24 22:21:29 2016.
Installed Packages
Name        : snapd
Arch        : x86_64
Epoch       : 0
Version     : 2.12
Release     : 1.fc24
Size        : 23 M
Repo        : @System
From repo   : zyga-snapcore
Summary     : The snapd and snap tools enable systems to work with .snap files
URL         : https://github.com/snapcore/snapd
License     : GPL-3
Description : Snappy is a modern, cross-distribution, transactional package manager designed for
            : working with self-contained, immutable packages.

Available Packages
Name        : snapd
Arch        : src
Epoch       : 0
Version     : 2.13
Release     : 1.fc24
Size        : 638 k
Repo        : zyga-snapcore
Summary     : The snapd and snap tools enable systems to work with .snap files
URL         : https://github.com/snapcore/snapd
License     : GPLv3
Description : Snappy is a modern, cross-distribution, transactional package manager designed for
            : working with self-contained, immutable packages.

Name        : snapd
Arch        : x86_64
Epoch       : 0
Version     : 2.13
Release     : 1.fc24
Size        : 5.9 M
Repo        : zyga-snapcore
Summary     : The snapd and snap tools enable systems to work with .snap files
URL         : https://github.com/snapcore/snapd
License     : GPLv3
Description : Snappy is a modern, cross-distribution, transactional package manager designed for
            : working with self-contained, immutable packages.

[fedora@ip-172-31-5-18 ~]$ snap -h
Usage:
  snap [OPTIONS] <command>

The snap tool interacts with the snapd daemon to control the snappy software platform.


Application Options:
      --version  print the version and exit

Help Options:
  -h, --help     Show this help message

Available commands:
  abort        Abort a pending change
  ack          Adds an assertion to the system
  buy          Buys a snap
  change       List a change's tasks
  changes      List system changes
  connect      Connects a plug to a slot
  create-user  Creates a local system user
  disable      Disables a snap in the system
  disconnect   Disconnects a plug from a slot
  enable       Enables a snap in the system
  find         Finds packages to install
  help         Help
  install      Installs a snap to the system
  interfaces   Lists interfaces in the system
  known        Shows known assertions of the provided type
  list         List installed snaps
  login        Authenticates on snapd and the store
  logout       Log out of the store
  refresh      Refreshes a snap in the system
  remove       Removes a snap from the system
  run          Run the given snap command
  try          Tests a snap in the system
[fedora@ip-172-31-5-18 ~]$ snap list
error: cannot list snaps: cannot communicate with server: Get http://localhost/v2/snaps: dial unix /run/snapd.socket: connect: no such file or directory
`

**Comment by zyga** [comment] 2016-08-26 07:36
Ah, this is temporary. We are waiting for a FESCo ticket to be approved. Then we will be able to auto-start those services automatically (this is the distribution policy, we cannot do it right now).

To start them manually just run this:
```
sudo systemctl enable snapd.socket
sudo systemctl start snapd.socket
```

**Comment by Conan-Kudo** [comment] 2016-08-26 10:15
Or, to be even quicker... 

```
sudo systemctl enable --now snapd.socket
```

**Comment by zyga** [comment] 2016-08-26 10:57
Oh, nice, thanks for the suggestion.

**Comment by manik-taneja** [comment] 2016-08-29 06:07
no luck-

```
[fedora@ip-172-31-5-18 ~]$ snap list
error: cannot list snaps: cannot communicate with server: Get http://localhost/v2/snaps: dial unix /run/snapd.socket: connect: no such file or directory
[fedora@ip-172-31-5-18 ~]$ sudo systemctl enable --now snapd.socket
Created symlink from /etc/systemd/system/sockets.target.wants/snapd.socket to /usr/lib/systemd/system/snapd.socket.
[fedora@ip-172-31-5-18 ~]$ snap list
error: cannot list snaps: cannot communicate with server: Get http://localhost/v2/snaps: dial unix /run/snapd.socket: connect: connection refused
[fedora@ip-172-31-5-18 ~]$ systemctl list-units | grep snap
● snapd.service                                     loaded failed failed    Snappy daemon
● snapd.socket                                      loaded failed failed    Socket activation for snappy daemon
[fedora@ip-172-31-5-18 ~]$ systemctl status snapd.socket
● snapd.socket - Socket activation for snappy daemon
   Loaded: loaded (/usr/lib/systemd/system/snapd.socket; enabled; vendor preset: disabled)
   Active: failed (Result: service-start-limit-hit) since Mon 2016-08-29 06:00:26 UTC; 3min 23s ago
   Listen: /run/snapd.socket (Stream)

Aug 29 06:00:21 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: Starting Socket activation for snappy daemon.
Aug 29 06:00:21 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: Listening on Socket activation for snappy daemon.
Aug 29 06:00:26 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: snapd.socket: Unit entered failed state.
[fedora@ip-172-31-5-18 ~]$ systemctl status snapd.service
● snapd.service - Snappy daemon
   Loaded: loaded (/usr/lib/systemd/system/snapd.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2016-08-29 06:00:26 UTC; 4min 12s ago
  Process: 27946 ExecStartPre=/usr/sbin/modprobe squashfs (code=exited, status=1/FAILURE)

Aug 29 06:00:26 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: Starting Snappy daemon...
Aug 29 06:00:26 ip-172-31-5-18.us-west-1.compute.internal modprobe[27946]: modprobe: FATAL: Module squashfs not found in directory /lib/modules/4.5.5-300.fc24.x86_64
Aug 29 06:00:26 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: snapd.service: Control process exited, code=exited status=1
Aug 29 06:00:26 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: Failed to start Snappy daemon.
Aug 29 06:00:26 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: snapd.service: Unit entered failed state.
Aug 29 06:00:26 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: snapd.service: Failed with result 'exit-code'.
Aug 29 06:00:26 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: snapd.service: Start request repeated too quickly.
Aug 29 06:00:26 ip-172-31-5-18.us-west-1.compute.internal systemd[1]: Failed to start Snappy daemon.
[fedora@ip-172-31-5-18 ~]$ find /lib/modules | grep squashfs
/lib/modules/4.5.5-300.fc24.x86_64/kernel/fs/squashfs
/lib/modules/4.6.6-300.fc24.x86_64/kernel/fs/squashfs
/lib/modules/4.6.6-300.fc24.x86_64/kernel/fs/squashfs/squashfs.ko.xz
[fedora@ip-172-31-5-18 ~]$ find /lib/modules | grep squashfs.ko
/lib/modules/4.6.6-300.fc24.x86_64/kernel/fs/squashfs/squashfs.ko.xz
[fedora@ip-172-31-5-18 ~]$ info systemctl
[fedora@ip-172-31-5-18 ~]$ systemctl restart snapd.service
Failed to restart snapd.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status snapd.service' for details.
[fedora@ip-172-31-5-18 ~]$ systemctl restart snapd
Failed to restart snapd.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status snapd.service' for details.
[fedora@ip-172-31-5-18 ~]$ cat /proc/filesystems | grep squashfs
[fedora@ip-172-31-5-18 ~]$ sudo modprobe squashfs
modprobe: FATAL: Module squashfs not found in directory /lib/modules/4.5.5-300.fc24.x86_64
[fedora@ip-172-31-5-18 ~]$ sudo modprobe squashfs.ko
modprobe: FATAL: Module squashfs.ko not found in directory /lib/modules/4.5.5-300.fc24.x86_64
```

**Comment by manik-taneja** [comment] 2016-08-29 06:11
also, i don't have the relevant permissions to re-open this issue. can you please re-open it until i am able to verify this.

**Comment by zyga** [comment] 2016-08-29 09:53
Looks like the issue is related to  `squashfs.ko`.

**Comment by Conan-Kudo** [comment] 2016-11-01 16:55
It looks like the issue is related to mismatched kernel / kernel-modules packages. Can you do `dnf distro-sync` and then reboot the machine into the latest installed kernel?

**Comment by megha-tank** [comment] 2016-12-28 06:09
I am preparing kernel snap via snapcraft command: After compiling source it gives the error related to squashfs module as listed below:

Generating driver initrd for kernel release: 4.4.9-linaro-lt-qcom
Parallel unsquashfs: Using 4 processors
2 inodes (27 blocks) to write

[================================================================================================================================|] 27/27 100%

created 1 files
created 4 directories
created 1 symlinks
created 0 devices
created 0 fifos
22303 blocks
modprobe: FATAL: Module squashfs not found in directory /home/megha/Linaro_16.06/parts/kernel/install/lib/modules/4.4.9-linaro-lt-qcom
Command '['/bin/sh', '/tmp/tmpzc0wvuqo', 'modprobe', '-n', '--show-depends', '-d', '/home/megha/Linaro_16.06/parts/kernel/install', '-S', '4.4.9-linaro-lt-qcom', 'squashfs']' returned non-zero exit status 1

When I compile the source with manually make command then it generates squashfs.ko
But from snapcraft command it gives this error.

By applying some commands to check related squashfs: 

$rpm -q --whatprovides "kmod(squashfs.ko)"
no package provides kmod(squashfs.ko)

$ cat /proc/filesystems 
nodev	sysfs
nodev	rootfs
nodev	ramfs
nodev	bdev
nodev	proc
nodev	cpuset
nodev	cgroup
nodev	tmpfs
nodev	devtmpfs
nodev	debugfs
nodev	tracefs
nodev	securityfs
nodev	sockfs
nodev	bpf
nodev	pipefs
nodev	devpts
	ext3
	ext2
	ext4
	squashfs
nodev	hugetlbfs
	vfat
nodev	ecryptfs
	fuseblk
nodev	fuse
nodev	fusectl
nodev	pstore
nodev	mqueue
nodev	autofs
nodev	binfmt_misc

Would you please help me to solve this issue?

**Comment by manik-taneja** [comment] 2017-01-12 08:57
Does the snapcore copr repo work with Fedora 25 cloud base image? I can't get it to work on AWS.. Do I need to continue to verify this on Fedora 24 only?

**Comment by zyga** [comment] 2017-01-12 11:53
None of the repositories are currently operational.

**Comment by zyga** [comment] 2017-02-17 15:37
I'm closing this issue now. Please report further bugs on the Fedora bug tracker after the release of 2.23 next week.

https://apps.fedoraproject.org/packages/snapd/bugs

**Closed by zyga** 2017-02-17 15:37 UTC
